
package com.mycompany.proyectofinalpoo;


import javax.swing.JButton;

public class Cobrar extends javax.swing.JFrame {

    /**
     * Creates new form Cobrar
     */
    public Cobrar() {
        initComponents();
    }
    
    public JButton retornaBttAceptar()
    {
        return btt_aceptar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nombre_negocio = new javax.swing.JLabel();
        img_1 = new javax.swing.JLabel();
        img_2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cuanto_paga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cambio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMetodoPago = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btt_aceptar = new javax.swing.JButton();
        btt_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PUNTO DE COBRO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, -1));

        nombre_negocio.setFont(new java.awt.Font("AR CENA", 1, 30)); // NOI18N
        nombre_negocio.setText("PLACITA EL MONO");
        jPanel1.add(nombre_negocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 40));
        jPanel1.add(img_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));
        jPanel1.add(img_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 15))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Total a pagar:");
        jPanel2.add(jLabel2);

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(204, 204, 204));
        txt_total.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel2.add(txt_total);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Con cuanto paga:");
        jPanel2.add(jLabel4);

        txt_cuanto_paga.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_cuanto_paga.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_cuanto_pagaInputMethodTextChanged(evt);
            }
        });
        txt_cuanto_paga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuanto_pagaActionPerformed(evt);
            }
        });
        txt_cuanto_paga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cuanto_pagaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cuanto_pagaKeyTyped(evt);
            }
        });
        jPanel2.add(txt_cuanto_paga);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Cambio:");
        jPanel2.add(jLabel3);

        txt_cambio.setEditable(false);
        txt_cambio.setBackground(new java.awt.Color(204, 204, 204));
        txt_cambio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(txt_cambio);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del cliente:");
        jPanel2.add(jLabel1);

        txt_nombre_cliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(txt_nombre_cliente);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Metodo de pago:");
        jPanel2.add(jLabel5);

        txtMetodoPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(txtMetodoPago);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 490, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 15))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout());

        btt_aceptar.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btt_aceptar.setText("Aceptar");
        btt_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btt_aceptar);

        btt_cancelar.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btt_cancelar.setText("Cancelar");
        btt_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btt_cancelar);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 490, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed

    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_cuanto_pagaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_cuanto_pagaInputMethodTextChanged

    }//GEN-LAST:event_txt_cuanto_pagaInputMethodTextChanged

    private void txt_cuanto_pagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuanto_pagaActionPerformed

    }//GEN-LAST:event_txt_cuanto_pagaActionPerformed

    private void txt_cuanto_pagaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuanto_pagaKeyReleased

    }//GEN-LAST:event_txt_cuanto_pagaKeyReleased

    private void txt_cuanto_pagaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuanto_pagaKeyTyped

    }//GEN-LAST:event_txt_cuanto_pagaKeyTyped

    private void btt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_aceptarActionPerformed

    }//GEN-LAST:event_btt_aceptarActionPerformed

    private void btt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_cancelarActionPerformed
        this.setRootPane(null);
        this.dispose();
    }//GEN-LAST:event_btt_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_aceptar;
    private javax.swing.JButton btt_cancelar;
    private javax.swing.JLabel img_1;
    private javax.swing.JLabel img_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel nombre_negocio;
    public javax.swing.JTextField txtMetodoPago;
    public javax.swing.JTextField txt_cambio;
    public javax.swing.JTextField txt_cuanto_paga;
    public javax.swing.JTextField txt_nombre_cliente;
    public javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
